version: '3'
services:
  radarr:
    image: linuxserver/radarr:4.2.4
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - ./data/radarr:/config
      - ./data/radarr-multimedia:/mnt/multimedia
      - ./data/multimedia:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
  sonarr:
    image: linuxserver/sonarr:3.0.9
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ./data/sonarr:/config
      - ./data/radarr-multimedia:/mnt/multimedia
      - ./data/multimedia:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
  jackett:
    image: linuxserver/jackett:0.20.2093
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - ./data/jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
  plex:
    image: lscr.io/linuxserver/plex:1.29.0
    container_name: plex
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./data/plex:/config
      - ./data/multimedia:/downloads-transmission
      - ./data/radarr-multimedia:/downloads-radarr
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi:4.22.5
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - BASE_URL=/ #optional
    volumes:
      - ./data/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:version-3.00-r5
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./data/transmission-config:/config
      - ./data/multimedia:/downloads
      - ./data/transmission-watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr:v2.2.9
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Madrid
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
