version: '3'
services:
  plex:
    image: lscr.io/linuxserver/plex:1.29.0
    container_name: plex
    ports:
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./data/plex:/config
      - ./data/multimedia:/downloads-transmission
      - ./data/radarr-multimedia:/downloads-radarr-sonarr
    restart: always
  transmission:
    image: lscr.io/linuxserver/transmission:3.00-r5-ls137
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./data/transmission-config:/config
      - ./data/multimedia:/downloads
      - ./data/transmission-watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #user: 1000:1000
    ports:
      - 8096:8096
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/cache:/cache
      - ./data/multimedia:/media
    restart: 'unless-stopped'
