version: '3'
services:
  radarr:
    image: linuxserver/radarr:4.2.4
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - radarr:/config
      - multimedia:/mnt/multimedia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

  sonarr:
    image: linuxserver/sonarr:3.0.9
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - sonarr:/config
      - multimedia:/mnt/multimedia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

  jackett:
    image: linuxserver/jackett:0.20.2093
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid

  lidarr:
    image: linuxserver/lidarr:1.0.2
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - lidarr:/config
      - multimedia:/mnt/multimedia
    ports:
      - 8686:8686
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi:4.22.5
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - BASE_URL=/ #optional
    volumes:
      - ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:version-3.00-r5
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - transmission-config:/config
      - transmission-downloads:/downloads
      - transmission-watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

volumes:
  radarr:
  sonarr:
  jackett:
  lidarr:
  ombi:
  multimedia:
  transmission-config:
  transmission-downloads:
  transmission-watch: